stages:
  preprocess:
    cmd: python preprocessing.py
    deps:
    - constants.py
    - preprocessing.py
    - raw_dataset/weatherHistory.csv
    outs:
    - processed_dataset/weatherHistory.csv
  train:
    cmd: python main.py
    deps:
    - constants.py
    - main.py
    - metrics_and_plots.py
    - processed_dataset/weatherHistory.csv
    - training.py
    outs:
    - plots/confusion_matrix.png
    - plots/metrics.json
